# Generated by Django 2.2.26 on 2022-02-09 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_page_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title']},
        ),
    ]
